---
abstract: 'code attribute introspection'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Tomas Doran <bobtfish@bobtfish.net>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092450'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-MethodAttributes
requires:
  Moose: 0.90
  MooseX::Types: 0.19
  Test::Exception: 0
  Test::More: 0
  namespace::clean: 0.10
version: 0.16_01
