---
abstract: code attribute introspection
author:
- Florian Ragwitz <rafl@debian.org>
- Tomas Doran <bobtfish@bobtfish.net>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.091260
license: perl
name: MooseX-MethodAttributes
requires:
  Moose: '0.79'
  MooseX::Types: '0.06'
  Test::Exception: '0'
  Test::More: '0'
  namespace::clean: '0'
version: '0.14'
