--- 
abstract: code attribute introspection
author: 
  - Florian Ragwitz <rafl@debian.org>
  - Tomas Doran <bobtfish@bobtfish.net>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.006
license: perl
name: MooseX-MethodAttributes
requires: 
  Moose: 0.70
  MooseX::Types: 0.06
  namespace::clean: 0
version: 0.06
