use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Florian
Ragwitz
rafl
Tomas
Doran
bobtfish
Dave
Rolsky
autarch
David
Steinbrunner
dsteinbrunner
Karen
Etheridge
ether
Marcus
Ramberg
marcus
Peter
Karman
pek
t0m
lib
MooseX
MethodAttributes
Inheritable
Role
Meta
Class
Application
AttrContainer
Method
Wrapped
Map
MaybeWrapped
Summation
